<a href="/usuarios/insert">Insert</a>
<table class="table table-striped">
<?php foreach ($data as $row):
    //$columnas = explode("|", $fila); ?>
    <tr>
        <?php foreach ($row as $key2 => $value): ?>
            <td><?=$value;?></td>
        <?php endforeach;?>
        <td>
            <a href="/usuarios/update/id/<?=$key;?>">Update</a> | 
            <a href="/usuarios/delete/id/<?=$key;?>">Delete</a>
        </td>
    </tr>
<?php endforeach;?>
</table>